# Use postgres/example user/password credentials
version: '3.9'

services:

    db:
        image: postgres
        restart: always
        # set shared memory limit when using docker-compose
        shm_size: 128mb
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: author-book
            POSTGRES_PASSWORD: password
        volumes:
            - ../../.docker/database/postgres/docker-entrypoint-initdb:/docker-entrypoint-initdb.d/
        ports:
            - 5432:5432

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
